version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faker
    versions:
    - 6.6.1
    - 6.6.3
    - 7.0.1
    - 8.0.0
    - 8.1.0
  - dependency-name: sqlalchemy
    versions:
    - 1.4.1
    - 1.4.3
  - dependency-name: starlette
    versions:
    - 0.14.2
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: idna
    versions:
    - "3.1"
  - dependency-name: pycodestyle
    versions:
    - 2.7.0
  - dependency-name: pyflakes
    versions:
    - 2.3.0
