version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=demando
      - POSTGRES_USER=demando
      - POSTGRES_PASSWORD=1234
  app:
    build: .
    command: uvicorn --app-dir src/ main:app --workers 4 --host 0.0.0.0 --port 8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
