"""upgrade to gino

Revision ID: 20e810dbaaf0
Revises: 
Create Date: 2021-03-27 23:13:50.925445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e810dbaaf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('verbose', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_roles_pk'), 'roles', ['pk'], unique=False)
    op.create_table('users',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_pk'], ['roles.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_pk'), 'users', ['pk'], unique=False)
    op.create_table('events',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_events_pk'), 'events', ['pk'], unique=False)
    op.create_table('polls',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_pk'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_polls_pk'), 'polls', ['pk'], unique=False)
    op.create_table('options',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('poll_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_pk'], ['polls.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_options_pk'), 'options', ['pk'], unique=False)
    op.create_table('questions',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('event_pk', sa.Integer(), nullable=True),
    sa.Column('author_pk', sa.Integer(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_pk'], ['users.pk'], ),
    sa.ForeignKeyConstraint(['event_pk'], ['events.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_questions_pk'), 'questions', ['pk'], unique=False)
    op.create_table('user_likes',
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('question_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_pk'], ['questions.pk'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['users.pk'], )
    )
    op.create_table('votes',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('poll_pk', sa.Integer(), nullable=True),
    sa.Column('owner_pk', sa.Integer(), nullable=True),
    sa.Column('option_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_pk'], ['options.pk'], ),
    sa.ForeignKeyConstraint(['owner_pk'], ['users.pk'], ),
    sa.ForeignKeyConstraint(['poll_pk'], ['polls.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_index(op.f('ix_votes_pk'), 'votes', ['pk'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_pk'), table_name='votes')
    op.drop_table('votes')
    op.drop_table('user_likes')
    op.drop_index(op.f('ix_questions_pk'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_options_pk'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_polls_pk'), table_name='polls')
    op.drop_table('polls')
    op.drop_index(op.f('ix_events_pk'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_pk'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_pk'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
