# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, poetry-version-management ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Bootstrap poetry
      shell: bash
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Configure poetry
        shell: bash
        run: python -m poetry config virtualenvs.in-project true

    - name: Install flake8
      run: |
        python3 -m poetry add flake8
    - name: Run flake8
      uses: julianwachholz/flake8-action@v1.1.0
      with:
        checkName: 'lint'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    needs: lint
    name: Test with pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 12.2
        postgresql db: 'demando'
        postgresql user: 'demando'
        postgresql password: '1234'

    - name: Cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        # This path is specific to Ubuntu
        path: /opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-pip3-
          ${{ runner.os }}-pytest-
    - name: Install dependencies
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.9.2/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.2/x64/lib
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip3 install -r requirements.txt
    - name: Test with pytest
      run: |
        cd src
        /opt/hostedtoolcache/Python/3.9.2/x64/bin/pytest --cov --cov-report=xml
      env:
        DB_NAME: demando
        DB_USER: demando
        DB_USER_PASSWORD: 1234
        DB_HOST: localhost
        POSTGRES_DB_HOST: 127.0.0.1

    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: src/junit/test-results.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Upload pytest coverage results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: coverage.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

  codecov:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: coverage.xml # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
